## Создание базы данных в Pandas

## Импорты библиотек

In [14]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
import pymorphy3
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to /home/stas/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /home/stas/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

## Массив для записи в его чанков, чанк это кусок лекции где слов чуть больше 500

In [2]:
array_of_chuncks = []

In [ ]:
# массив с названиями файлов в дериктории ./student_book_txt
array_of_books = [book for book in os.listdir('./student_book_txt')]

NameError: name 'os' is not defined

In [ ]:
# алгоритм деления на чанки текста с ./student_book_txt
idx_chunk = 0
count_word = 0
for book in tqdm(array_of_books):
    with open(f'./student_book_txt/{book}', 'r', encoding='utf-8') as file:
        line = file.readline()
        while line:
            count_word += len(line.split())
            try:
                array_of_chuncks[idx_chunk] += line
            except IndexError as err:
                array_of_chuncks.append(line)
            if count_word > 500:
                idx_chunk += 1
                count_word = 0
            line = file.readline()
        idx_chunk += 1
        count_word = 0

NameError: name 'array_of_books' is not defined

In [5]:
array_of_chuncks

['кафедра «Математическое моделирование»\nпроф. П. Л. Иванков\nИнтегралы и дифференциальные уравнения\nконспект лекций\nдля студентов 1-го курса 2-го семестра\nспециальностей РЛ1,2,3,6, БМТ1,2\nЛекция 24\nОднородные системы линейных дифференциальных уравнений с по-\nстоянными коэффициентами. Характеристическое уравнение си-\nстемы. Построение общего решения по корням характеристического\nуравнения (вывод только для случая действительных и различных\nкорней).\nРассмотрим линейную однородную систему с постоянными коэффициентами\nn\nX\ny0 = a y , i = 1,...,n . (1)\ni ij j\nj=1\nВ матричной форме эта система запишется так:\nY0 = AY , (2)\nгде\n\uf8eb \uf8f6\na a ... a\n\uf8eb \uf8f6 11 12 1n\ny\n1 a a ... a\n\uf8ec 21 22 2n \uf8f7\nY = \uf8ed ... \uf8f8 , A = \uf8ec \uf8f7 .\n··················\n\uf8ed \uf8f8\ny\nn\na a ... a\nn1 n2 nn\nХарактеристическим уравнением системы (1) (или (2)) называется уравнение\n \na −λ a ... a\n 11 12 1n \n \na a −λ ... a\n 21 22 2n \n  = 0 .\n ··························· \n \n a a ... a −λ \nn1 n2 nn\nЕсли корни характеристического уравнения вещественны и различны, то нетрудно по-\nстроить фундаментальную систему решений системы (1). В самом деле, обозначим эти\nкорни λ ,...,λ и для каждого корня найдем отвечающий ему собственный вектор:\n1 n\n\uf8eb \uf8f6 \uf8eb \uf8f6\nα α\n11 1n\nE 1 = \uf8ed ... \uf8f8 ,..., E n = \uf8ed ... \uf8f8 .\nα α\nn1 nn\nЗаметим теперь, что вектор-функции\nY = eλixE , i = 1,...,n ,\ni i\n1\nявляются решениями системы (2):\nY0 = λ eλixE = eλixAE = A(eλixE ) = AY , т.е. Y0 = AY , i = 1,...,n .\ni i i i i i i i\nПроверим, что Y ,...,Y линейно независимы; для этого составим определитель Врон-\n1 n\nского:\n \nα α ... α\n 11 12 1n \n \nα α ... α\nW(x) = e(λ1+...+λn)x ·   21 22 2n   6= 0 ,\n ·················· \n \n α α ... α \nn1 n2 nn\nт.к. собственные векторы, отвечающие различным собственным значениям, линейно не-\nзависимы. Мы видим, что решения Y ,...,Y действительно образуют фундаментальную\n1 n\nсистему решений системы (2).\nПример. Пусть дана система\n(\ny0 = y +3y ,\n1 1 2\ny0 = 3y +y .\n2 1 2\nСоставляем характеристическое уравнение и находим его корни:\n \n 1−λ 3 \n  = λ2 −2λ−8 = 0 , λ = −2 ,λ = 4 .\n 3 1−λ  1 2\nСобственные векторы, отвечающие найденным собственным значениям, определяем из\nсистем:\n( (\n3α +3α = 0 , −3α +3α = 0 ,\n11 21 12 22\n3α +3α = 0 , 3α −3α = 0 .\n11 21 12 22\nВ качестве собственных векторов можно взять\n   \n−1 1\nE = , E = .\n1 1 2 1\nФундаментальную систему решений образуют вектор-функции\n   \n−1 1\nY = e−2x · и Y = e4x · .\n1 1 2 1\nОбщее решение имеет вид\n   \n−1 1\nY = C e−2x · +C e4x · ;\n1 1 2 1\nв координатах\ny = −C e−2x +C e4x , y = C e−2x +C e4x .\n',
 '1 1 2 2 1 2\nТ.к. коэффициенты характеристического уравнения системы (2) вещественны, то его\nкомплексные корни распадаются на пары комплексно сопряженных. Для каждой пары\nα±iβ, β 6= 0, можно построить два линейно независмых решения системы (2).\nНайдем ненулевой комплексный вектор\n\uf8eb \uf8f6 \uf8eb \uf8f6\nα β\n1 1\nZ = \uf8ed ... \uf8f8+i \uf8ed ... \uf8f8 ,\nα β\nn n\n2\nдля которого AZ = (α + iβ)Z. Как и в вещественном случае нетрудно проверить, что\nкомплекснозначная функция\n\uf8eb \uf8f6 \uf8eb \uf8f6 \uf8eb \uf8eb \uf8f6 \uf8eb \uf8f6\uf8f6\nα β β α\n1 1 1 1\ne(α+iβ)xZ = eαxcosβx\uf8ed...\uf8f8−eαxsinβx\uf8ed...\uf8f8+i\uf8edeαxcosβx\uf8ed...\uf8f8+eαxsinβx\uf8ed...\uf8f8\uf8f8\nα β β α\nn n n n\nявляется решением системы (2). Отсюда получаем два вещественных решения этой си-\nстемы:\n\uf8eb \uf8f6 \uf8eb \uf8f6\nα β\n1 1\nX = eαxcosβx \uf8ed ... \uf8f8−eαxsinβx \uf8ed ... \uf8f8 ,\nα β\nn n\n\uf8eb \uf8f6 \uf8eb \uf8f6\nβ α\n1 1\nY = eαxcosβx \uf8ed ... \uf8f8+eαxsinβx \uf8ed ... \uf8f8 .\nβ α\nn n\nНа доказательстве линейной независимости решений X и Y не останавливаемся.\nЗадача (для желающих). Доказать, что решения X и Y линейно независимы.\nПример. Пусть требуется найти общее решение системы\n(\ny0 = y −3y ,\n1 1 2\ny0 = 3y +y .\n2 1 2\nСоставляем и решаем характеристическое уравнение:\n \n 1−λ −3 \n  = (1−λ)2 +9 = 0 , λ = 1±3i .\n 3 1−λ  1,2\n”Комплексный собственный вектор”\n \nz\nZ = 1\nz\n2\nнаходим из системы:\n    \n−3i −3 z 0\n1 = ;\n3 −3i z 0\n2\n(\n−3iz −3z = 0 ,\n1 2\n3z −3iz = 0 .\n1 2\nОтсюда видно, что в качестве компонент Z можно взять z = 1, z = −i. Комплексно-\n1 2\nзначное решение системы есть\n     \n1 0 cos3x+isin3x\ne(1+3i)x +i = ex .\n0 −1 sin3x−icos3x\nОтделяя вещественную и мнимую части, получаем фундаментальную систему решений\nисходной системы:\n   \ncos3x sin3x\nY = ex и Y = ex .\n1 sin3x 2 −cos3x\nОтсюда находим общее решение:\n   \ncos3x sin3x\nY = C ex +C ex ,\n1 sin3x 2 −cos3x\n3\nили в координатах\ny = ex(C cos3x+C sin3x) ,\n1 1 2\ny = ex(C sin3x−C cos3x) .\n2 1 2\nЕсли среди корней характеристического уравнения имеются кратные, то следует для ка-\nждого вещественного корня λ кратности r найти размерность m соответствующего про-\nстранства собственных векторов. Если m = r, то, взяв базис E ,...,E этого простран-\n1 r\nства, получим для λ в точности r линейно независимых решений системы (2):\nY = eλxE , i = 1,...,r .\ni i\nЕсли m < r, то найти r линейно независимых решений для λ можно методом неопределен-\nных коэффициентов. При этом решения следует искать в виде\nY = (C +C x+...+C xr−m)eλx , (3)\n0 1 r−m\nгде\n\uf8eb \uf8f6 \uf8eb \uf8f6\nC C\n10 1,r−m\nC 0 = \uf8ed ... \uf8f8 ,... , C r−m = \uf8ed ...... \uf8f8\nC C\nn0 n,r−m\n–столбцы,компонентыкоторыхподлежатопределению. ДляэтогоY подставляютвисход-\nную систему, сокращают обе части на eλx и приравнивают коэффициенты при одинаковых\n',
 'степенях x слева и справа. В результате получается система линейных однородных алге-\nбраических уравнений, которой удовлетворяют компоненты столбцов C ,...,C . Решая\n0 r−m\nэту систему, можно получить r линейно независимых решений исходной системы диффе-\nренциальных уравнений.\nКак известно, комплексные корни (не являющиеся вещественными) уравнения с веще-\nственными коэффициентами распадаются на пары комплексно сопряженных корней одной\nи той же кратности. Если α±iβ, β 6= 0, – одна из таких пар кратности r, то описанную\nвыше процедуру следует применить в комплексном случае для одного из корней α + iβ,\nа затем отделить в полученных комплекснозначных решениях вещественную и мнимую\nчасти. Проделаввсеэтодлякаждогокорняхарактеристическогоуравнения, получимфун-\nдаментальную систему решений для исходной системы дифференциальных уравнений.\nПример. Пусть требуется найти фундаментальную систему решений системы урав-\nнений\n\uf8f1\ny0 = y +2y +y ,\n\uf8f4 \uf8f2 1 1 2 3\ny0 = −y +4y +y ,\n2 1 2 3\n\uf8f4\n\uf8f3 y0 = −y +2y +3y .\n3 1 2 3\nСоставим и решим характеристическое уравнение:\n     \n 1−λ 2 1   2−λ λ−2 0   1 −1 0 \n     \n0 =  −1 4−λ 1  =  −1 4−λ 1  = (2−λ)· −1 4−λ 1  =\n     \n −1 2 3−λ   −1 2 3−λ   −1 2 3−λ \n \n 1 0 0 \n   \n= (2−λ)· −1 3−λ 1  = (2−λ) (3−λ)2−1 = (2−λ)2(4−λ); λ = λ = 2, λ = 4.\n1 2 3\n \n 1 1 3−λ \nДля собственного значения λ = λ = 2 матрица однородной системы, которой удовлетво-\n1 2\nряют компоненты собственных векторов, имеет вид\n\uf8eb \uf8f6\n−1 2 1\n\uf8ed −1 2 1 \uf8f8 .\n−1 2 1\n4\nЗдесь без труда находим два линейно независимых собственных вектора, отвечающих\nэтому собственному значению:\n\uf8eb \uf8f6 \uf8eb \uf8f6\n2 1\nE 1 = \uf8ed 1 \uf8f8 и E 2 = \uf8ed 0 \uf8f8 ;\n0 1\nэтим собственным векторам отвечают два линейно независимых решения рассматривае-\nмой системы:\n\uf8eb \uf8f6 \uf8eb \uf8f6\n2 1\nY 1 = e2x \uf8ed 1 \uf8f8 и Y 2 = e2x \uf8ed 0 \uf8f8 .\n0 1\nДля собственного значения λ = 4 соответствующую матрицу однородной системы приве-\n3\nдем к ступенчатому виду:\n\uf8eb \uf8f6 \uf8eb \uf8f6 \uf8eb \uf8f6\n−3 2 1 −1 0 1 −1 0 1\n\uf8ed −1 0 1 \uf8f8 ∼ \uf8ed 0 2 −2 \uf8f8 ∼ \uf8ed 0 1 −1 \uf8f8 .\n−1 2 −1 0 2 −2 0 0 0\nВ качестве собственного вектора можно взять\n\uf8eb \uf8f6\n1\nE 3 = \uf8ed 1 \uf8f8 ;\n1\nэтому вектору соответствует такое решение исходной системы\n\uf8eb \uf8f6\n1\nY 3 = e4x \uf8ed 1 \uf8f8 .\n1\nТребуемая фундаментальная система решений найдена:\n\uf8eb \uf8f6 \uf8eb \uf8f6 \uf8eb \uf8f6\n2 1 1\nY 1 = e2x \uf8ed 1 \uf8f8 , Y 2 = e2x \uf8ed 0 \uf8f8 , Y 3 = e4x \uf8ed 1 \uf8f8 .\n0 1 1\nПример 2. Найдем фундаментальную систему решений для системы дифференциаль-\nных уравнений\n(\ny0 = y +y ,\n1 1 2\ny0 = −y +3y .\n2 1 2\nСоставляем и решаем характеристическое уравнение:\n \n 1−λ 1 \n0 =   = (λ−2)2 , λ = λ = 2 .\n',
 ' −1 3−λ  1 2\nДля определения компонент собственных векторов имеем однородную систему линейных\nалгебраических уравнений с матрицей\n \n−1 1\n.\n−1 1\nЗдесь пространство собственных векторов имеет размерность m = 1, т.е. меньше кратно-\nсти r = 2 соответствующего собственного значения. Поэтому решение исходной системы\nищем в виде\nY = (C +C x)e2x ,\n0 1\n5\n   \nc c\nгде C = 10 , C = 11 .\n0 c 1 c\n20 21\nНаходим производную\nY0 = (C +2C +2C x)e2x\n1 0 1\nи подставляем в исходную систему; после сокращения на e2x получаем\nC +2C +2C x = A(C +C x) ,\n1 0 1 0 1\nили\n(\nC +2C = AC ,\n1 0 0\n2C = AC ,\n1 1\n \n1 1\nгде A = .\n−1 3\nОтсюда такая система для определения компонент векторов C и C :\n0 1\n\uf8f1\nc +2c = c +c ,\n\uf8f4 11 10 10 20\n\uf8f4\n\uf8f4\n\uf8f2 c +2c = −c +3c ,\n21 20 10 20\n2c = c +c ,\n\uf8f4 \uf8f4 11 11 21\n\uf8f4\n\uf8f3 2c = −c +3c .\n21 11 21\nУпорядочив неизвестные, получим\n\uf8f1\nc −c +c = 0 ,\n\uf8f4 10 20 11\n\uf8f4\n\uf8f4\n\uf8f2 c −c +c = 0 ,\n10 20 21\nc −c = 0 ,\n\uf8f4 \uf8f4 11 21\n\uf8f4\n\uf8f3 c −c = 0 .\n11 21\nМатрицу этой системы приведем к ступенчатому виду:\n\uf8eb \uf8f6\nI III II IV\n\uf8eb \uf8f6 \uf8eb \uf8f6\n1 −1 1 0 1 −1 1 0\n\uf8ec 1 1 −1 0 \uf8f7\n\uf8ec 1 −1 0 1 \uf8f7 \uf8ec 0 0 −1 1 \uf8f7 \uf8ec \uf8f7\n\uf8ec \uf8f7 ∼ \uf8ec \uf8f7 ∼ \uf8ec 0 −1 0 1 \uf8f7 .\n\uf8ed 0 0 1 −1 \uf8f8 \uf8ed 0 0 0 0 \uf8f8 \uf8ec \uf8f7\n\uf8ed 0 0 0 0 \uf8f8\n0 0 1 −1 0 0 0 0\n0 0 0 0\nНеизвестные c и c – базисные, c и c – свободные. Фундаментальную систему реше-\n10 11 20 21\nний образуют решения\n\uf8eb \uf8f6 \uf8eb \uf8f6\n1 −1\n\uf8ec \uf8ec 1 \uf8f7 \uf8f7 и \uf8ec \uf8ec 0 \uf8f7 \uf8f7 ,\n\uf8ed 0 \uf8f8 \uf8ed 1 \uf8f8\n0 1\nт.е.\n   \n1 0\nC(1) = , C(1) = ;\n0 1 1 0\n   \n−1 1\nC(2) = , C(2) = .\n0 0 1 1\nОтсюда такая фундаментальная система решений исходной системы дифференциальных\nуравнений:\n     \n1 −1 1\nY = e2x , Y = +x e2x .\n1 1 2 0 1\n6\n',
 'кафедра «Математическое моделирование»\nпроф. П. Л. Иванков\nИнтегралы и дифференциальные уравнения\nконспект лекций\nдля студентов 1-го курса 2-го семестра\nспециальностей РЛ1,2,3,6, БМТ1,2\nЛекция 16\nГеометрическая интерпретация дифференциального уравнения пер-\nвого порядка. Изоклины. Геометрическое решение дифференциаль-\nных уравнений с помощью изоклин. Особые точки и особые решения\nдифференциального уравнения первого порядка.\nРассмотримдифференциальноеуравнениепервогопорядка, разрешенноеотносительно\nпроизводной\ny0 = f(x,y) , (1)\nгде правая часть определена на области G плоскости переменных x,y. Такое дифференци-\nальное уравнение устанавливает связь между координатами точки M(x,y) ∈ G и угловым\nкоэффициентом касательной y0(x) к интегральной кривой y = y(x), проходящей через эту\nточку:\ntgα = y0(x) = f(x,y) .\ny\nM α\nG\nO x\nРис.6\nКасательным вектором к этой кривой в указанной точке является вектор\n   \n1,y0(x) = 1,f(x,y) .\nЕсли каждой точке M(x,y) ∈ G поставить в соответствие такой вектор, то мы получим в\nобласти G поле направлений. Интегральные кривые – это те кривые, для которых вектор\n 1,f(x,y)  является касательным в соответствующей точке. Поэтому, если в области G\nвыбрать достаточно густую сеть точек и в каждой точке M(x,y) нарисовать исходящий из\nэтой точки вектор с координатами  1,f(x,y)  , то можно приближенно изобразить инте-\nгральные кривые уравнения (1), проводя эти кривые так, чтобы они в каждой своей точке\nкасались векторов построенного поля направлений. Построение поля направлений облег-\nчается использованием изоклин. Изоклиной дифференциального уравнения (1) называется\nмножество точек плоскости, в каждой из которых угловой коэффициент касательной к ин-\nтегральным кривым этого уравнения имеет постоянное значение. Очевидно, уравнение\nизоклины имеет вид\nf(x,y) = k ,\n1\nгде k – упомянутое в определении изоклины постоянное значение углового коэффициента\nкасательной. Таким образом, изоклины являются линиями уровня функции f(x,y) из\nправой части уравнения (1).\nПример. Пусть дано уравнение\ny0 = x2 −y2 .\nОбластью определения правой части является вся плоскость переменных x,y. Уравнения\nизоклин имеют вид\nx2 −y2 = k .\nПри k = 0 имеем пару вещественных пересекающихся прямых (биссектрис координат-\nных углов). При построении поля направлений (чтобы не загромождать чертеж) будем\nрисовать не векторы, а короткие отрезки прямых, проходящих через точки построенных\nизоклин и имеющих соответствующие угловые коэффициенты. При k 6= 0 изоклинами\nявляются гиперболы.\nРис.7\nПусть снова имеется дифференциальное уравнение\ny0 = f(x,y) , (1)\nправая часть которого определена на области G плоскости переменных x,y. Если для\nточки M(x ,y ) ∈ G найдутся две интегральные кривые, проходящие через эту точку и не\n0 0\nсовпадающие ни в какой ее окрестности, или через эту точку не проходит ни одна инте-\nгральная кривая, то M называется особой точкой данного дифференциального уравнения.\nТочка, не являющаяся особой, называется обыкновенной. В частности, обыкновенными\nявляются все точки, имеющие окрестность, в которой выполняются требования теоремы\nсуществования и единственности. Решение уравнения (1) называется особым, если все\nточки соответствующей интегральной кривой суть особые точки этого дифференциаль-\nного уравнения.\nПример. Рассмотрим уравнение\ny0 = 3y 2 .\n3\n2\nЗдесь правая часть определена на всей плоскости переменных x,y; условия теоремы су-\nществования и единственности нарушены в точках оси OX, т.к. при y = 0 функция\nf(x,y) = 3y2/3 не имеет частной производной по переменной y. Т.к. данное уравнение\nявляется уравнением с разделяющимися переменными, то в каждой из областей y > 0 или\n',
 'y < 0 можно без труда найти общее решение\ny = (x+C)3.\nЯсно, что при любом фиксированном значении C эта формула дает решение рассматри-\nваемого уравнения, заданное при всех значениях x. С другой стороны y ≡ 0 также есть\nрешение этого уравнения. Последнее решение является особым, т.к. через каждую точку\nсоответствующейинтегральнойкривой(вданномслучаеосиабсцисс)проходитнеменьше\nдвух интегральных кривых этого уравнения.\nЕсли точка M(x ,y ) лежит на интегральной кривой, отвечающей особому решению\n0 0\ny = y(x), то через эту точку проходит и другая интегральная кривая y = y (x) данного\n1\nдифференциального уравнения. Т.к. y0(x ) = y0(x ) = f(x ,y ), то эти кривые имеют\n1 0 0 0 0\nобщую касательную в точке M. Это простое замечание позволяет использовать для на-\nхождения особых решений понятие огибающей из теории кривых.\nПусть имеется семейство плоских кривых\nΦ(x,y,C) = 0 , (2)\nзависящих от параметра C. При каждом фиксированном C уравнение (2) задает неявно\nсоответствующую кривую этого семейства.\nКривая γ называется огибающей семейства (2), если в каждой своей точке γ каса-\nется некоторой кривой этого семейства, не совпадая с ней ни в какой окрестности ука-\nзанной точки. Если (2) задает семейство решений дифференциального уравнения (1),\nто огибающая этого семейства также будет решением (очевидно, особым) этого урав-\nнения если только эта огибающая может быть задана уравнением y = y(x)  . Дей-\nствительно, если y = y(x) – уравнение огибающей и x – произвольная точка из обла-\n0\nсти определения функции y(x), то для некоторого решения y = y (x) данного уравнения\n1\ny(x ) = y (x ) и y0(x ) = y0(x ). Поэтому из равенства y0(x ) = f  x ,y (x )  следует, что\n0 1 0 0 1 0 1 0 0 1 0\ny0(x ) = f  x ,y(x )  . Т.к. x – произвольная точка из области определения функции y(x),\n0 0 0 0\nто y(x) – решение уравнения (1).\nЧтобы составить уравнение огибающей, можно рассуждать следующим образом. Если\nγ касается кривых семейства (2), отвечающих изменению параметра C на интервале\nC < C < C , то на этом интервале γ можно задавать параметрически уравнениями\n1 2\nx = ϕ(C) , y = ψ(C) .\nВ таком случае должно выполняться равенство\n \nΦ ϕ(C),ψ(C),C = 0 ,\nт.к. в точке  ϕ(C),ψ(C)  кривая γ и кривая семейства (2), отвечающая данному зна-\nчению параметра C, имеют общую точку. Чтобы записать условие наличия общей ка-\nсательной, найдем соответствующие угловые коэффициенты. Для γ угловой коэффици-\nент касательной в точке кривой, отвечающей значению C параметра, равен ψ0(C)  ϕ0(C).\nПредположим, что функция Φ(x,y,C) имеет непрерывные частные производные по всем\nпеременным, и\n(Φ0)2 +(Φ0)2 > 0 .\nx y\n3\nПусть, для определенности, в окрестности точки (x,y) кривой Φ(x,y,C) = 0 отлична от\nнуля производная Φ0. Из теоремы о неявной функции, рассматриваемой в теории функ-\ny\nций нескольких переменных, следует, что тогда угловой коэффициент касательной к этой\nкривой в указанной точке есть\nΦ0(x,y,C)\n− x .\nΦ0(x,y,C)\ny\nПоэтому условие наличия общей касательной запишется в виде\n \nψ0(C) Φ0 ϕ(C),ψ(C),C\n= − x .\n \nϕ0(C) Φ0 ϕ(C),ψ(C),C\ny\n',
 'Отсюда\nΦ0 ·ϕ0(C)+Φ0 ·ψ0(C) = 0 .\nx y\nТаким образом, для функций ϕ(C) и ψ(C) выполняются равенства\n \nΦ ϕ(C),ψ(C),C = 0 ,\n(3)\nΦ0 ·ϕ0(C)+Φ0 ·ψ0(C) = 0 ,\nx y\nгдезначениячастныхпроизводныхфункцииΦвычисляютсявточке ϕ(C),ψ(C),C  . Про-\nдифференцируем по C первое из этих равенств:\nΦ0 ·ϕ0(C)+Φ0 ·ψ0(C)+Φ0 = 0 .\nx y C\nС учетом (3) получаем отсюда такие необходимые условия того, чтобы кривая γ была\nогибающей семейства Φ(x,y,C) = 0 :\n  )\nΦ ϕ(C),ψ(C),C = 0\n(4)\n \nΦ0 ϕ(C),ψ(C),C = 0\nC\nИз этой системы можно, в принципе, найти ϕ(C) и ψ(C). Если переписать последние\nравенства в виде\n)\nΦ(x,y,C) = 0\n, (5)\nΦ (x,y,C) = 0\nC\nто, исключив C, можно получить неявное уравнение кривой γ. Заметим, что условия\n(4) или (5) лишь необходимы для того, чтобы определяемая ими кривая была огибающей,\nдостаточными эти условия не являются. Поэтому, найдя параметрические уравнения кри-\nвой из (4) или неявное уравнение из (5), следует проверить, действительно ли найденная\nкривая является огибающей.\nПример. Рассмотрим дифференциальное уравнение\ny0 = 3(y −sinx)2/3 +cosx . (6)\nНепосредственной проверкой нетрудно убедиться, что при любом C функция\ny = (x+C)3 +sinx (7)\nестьрешениеэтогоуравнения. Здесьсемействоинтегральныхкривыхзадаетсяспомощью\nфункции\nΦ(x,y,C) = y −(x+C)3 −sinx .\n4\nДля нахождения уравнения огибающей имеем систему\n)\nΦ(x,y,C) = y −(x+C)3 −sinx = 0\n.\nΦ0 (x,y,C) = −3(x+C)2 = 0\nC\nОтсюда x + C = 0, и y = sinx. Надо еще проверить, что последнее равенство задает\nогибающую. Легко видеть, что при x = x кривые y = sinx и y = (x−x )3 +sinx имеют\n0 0\nобщую касательную в точке с абсциссой x = x . Поэтому y = sinx – огибающая семейства\n0\nкривых (7) и, следовательно, особое решение уравнения (6).\n5\n',

## Создание импровезированной бд с помощью pandas

In [ ]:
df = pd.DataFrame(array_of_chuncks, columns=['chunc_text'])

In [ ]:
# из-за перевода в csv можно теперь работать с df с помощью read_csv
df = pd.read_csv("database.csv")

In [5]:
df.head()

                                          chunc_text
0  кафедра «Математическое моделирование» проф. П...
1  1 1 2 2 1 2 Т.к. коэффициенты характеристическ...
2  степенях x слева и справа. В результате получа...
3   −1 3−λ  1 2 Для определения компонент собстве...
4  кафедра «Математическое моделирование» проф. П...

In [6]:
# замена переходов на следующую строку на обычные пробелы
df['chunc_text'] = df['chunc_text'].str.replace('\n', ' ')

In [7]:
#  перевод в нижний регистр всех текстов
df['chunc_text'] = df['chunc_text'].str.casefold()

In [8]:
df.head()

                                          chunc_text
0  кафедра «математическое моделирование» проф. п...
1  1 1 2 2 1 2 т.к. коэффициенты характеристическ...
2  степенях x слева и справа. в результате получа...
3   −1 3−λ  1 2 для определения компонент собстве...
4  кафедра «математическое моделирование» проф. п...

In [16]:
# загружаю stop_words (предлоги и приставки)
russian_stop_words = set(stopwords.words('russian'))

## Токенизация с помощью nltk и лэмматизация pymorphy3

In [18]:
morph = pymorphy3.MorphAnalyzer()
new_data_for_data_frame = []
cache = {}
for idx in range(len(df)):
    chunk = df.iloc[idx]['chunc_text']
    chunk = word_tokenize(chunk, language='russian')
    tokenize_chunk = [w for w in chunk if w.isalpha() and w not in russian_stop_words]
    for i, word in enumerate(tokenize_chunk):
        if word not in cache:
            cache[word] = morph.parse(word)[0].normal_form
        tokenize_chunk[i] = cache[word]
    new_data_for_data_frame.append(tokenize_chunk)

In [19]:
df['tokinaze_chunk'] = pd.Series(new_data_for_data_frame)

In [21]:
df.iloc[2]['tokinaze_chunk']

['степень',
 'x',
 'слева',
 'справа',
 'результат',
 'получаться',
 'система',
 'линейный',
 'однородный',
 'браический',
 'уравнение',
 'который',
 'удовлетворять',
 'компонент',
 'столбцы',
 'c',
 'c',
 'решать',
 'система',
 'получить',
 'r',
 'линейно',
 'независимый',
 'решение',
 'исходный',
 'система',
 'ренциальный',
 'уравнение',
 'известно',
 'комплексный',
 'корень',
 'являться',
 'вещественный',
 'уравнение',
 'ственный',
 'коэффициент',
 'распадаться',
 'пара',
 'комплексно',
 'сопрячь',
 'корень',
 'один',
 'тот',
 'кратность',
 'β',
 'один',
 'такой',
 'пара',
 'кратность',
 'r',
 'описать',
 'выше',
 'процедура',
 'следовать',
 'применить',
 'комплексный',
 'случай',
 'один',
 'корень',
 'α',
 'iβ',
 'затем',
 'отделить',
 'получить',
 'комплекснозначный',
 'решение',
 'вещественный',
 'мнимый',
 'часть',
 'проделаввсеэтодлякаждогокорняхарактеристическогоуравнение',
 'даментальный',
 'система',
 'решение',
 'исходный',
 'система',
 'дифференциальный',
 'уравнение',
 'пример',
 'пусть',
 'требоваться',
 'найти',
 'фундаментальный',
 'система',
 'решение',
 'система',
 'нения',
 'y',
 'составить',
 'решить',
 'характеристический',
 'уравнение',
 'λ',
 'λ',
 'λ',
 'собственный',
 'значение',
 'λ',
 'λ',
 'матрица',
 'однородный',
 'система',
 'который',
 'рять',
 'компонент',
 'собственный',
 'вектор',
 'иметь',
 'вид',
 'труд',
 'находить',
 'линейно',
 'независимый',
 'собственный',
 'вектор',
 'отвечать',
 'этот',
 'собственный',
 'значение',
 'e',
 'e',
 'это',
 'собственный',
 'вектор',
 'отвечать',
 'линейно',
 'независимый',
 'решение',
 'система',
 'y',
 'y',
 'собственный',
 'значение',
 'λ',
 'соответствовать',
 'матрица',
 'однородный',
 'система',
 'дем',
 'ступенчатый',
 'вид',
 'качество',
 'собственный',
 'вектор',
 'взять',
 'e',
 'этот',
 'вектор',
 'соответствовать',
 'такой',
 'решение',
 'исходный',
 'система',
 'y',
 'требовать',
 'фундаментальный',
 'система',
 'решение',
 'найти',
 'y',
 'y',
 'y',
 'пример',
 'найти',
 'фундаментальный',
 'система',
 'решение',
 'система',
 'ных',
 'уравнение',
 'y',
 'составлять',
 'решать',
 'характеристический',
 'уравнение',
 'λ',
 'λ']

In [5]:
import pandas as pd
corpus = list(pd.read_csv("../database.csv")['lemma_text'])
isinstance(corpus[0], str)

True

In [ ]:
"дисперсия" in corpus[852]
print(corpus[852])

распределение закон распределение быть говорить характеристика распределение математический ожидание случайный величина определение математический ожидание средний значение mx дискретный случайный величина x называть сумма произведение значение x cлучайный величина i ность p который случайный величина принимать значение i i x p i i i множество возможный значение cлучайный величина x счётный предполагаться i i ряд определять математический ожидание сходиться абсолютно противный случай рят математический ожидание случайный величина x существовать ник пусть прямой расположить система материальный точка масса p p пусть i i i x координата точка центр масса система иметь координата i x p x p i i i i i i x p p i i i i i совпадать математический ожидание mx случайный величина пример пусть x число выпасть очко подбрасывание игральный кость p i i определение математический ожидание средний значение mx непрерывный случайный величина называть интеграл xp x dx предполагаться x dx несобственный интеграл определять математический ожидание сходиться абсолютно такжекакивдискретномслучай математическоеожиданиенепрерывнойслучайнойвеличина интерпретировать центр масса стержень плотность масса который точка x равный p x пример случайный величина x иметь распределение кош распределение стьюp x π π πx поэтому математический ожидание случайный величина x существовать математический ожидание функция случайный величина найти математический ожидание функция случайный величина случайный вектор пусть y φ x являться функция случайный величина рассмотримсначаладискретнуюслучайнуювеличина x принимающуюзначенияx x n вероятностямиp тогдаслучайнаявеличинаy x принимаетзначение n n φ x вероятность p x математический ожидание определяться n n n формула my x φ x p i i требоваться выполнение условие x i i длянепрерывнойслучайнойвеличина x имеющейплотностьраспределение p x скоеожиданиеслучайнойвеличиныy x можнонайти используяаналогичный формула my x φ x p x dx причём требоваться выполнение условие x x dx дисперсия момент высокий порядок два случайный величина мочь иметь одинаковый средний значение возможный значение быть рассеиваться вокруг среднее например средний балл экзамен два группа равный первый группа студент получить второй группа верочник вообще пятёрочник троечник поэтому нарядусый средний значение хотелосьба иметь число характеризовать разброс случайный величина относительно свой среднее значение характеристика обычно жито дисперсия определение дисперсия dx случайный величина x называть математический ожидание квадрат отклонение случайный величина x среднее значение использовать формула который положить y x легко написать ные формула дисперсия дискретный непрерывный случайный величина соответственно x i i i x dx пример пусть x число выпасть очко подбрасывание игральный кость

In [11]:
df = pd.read_csv("../database.csv")['lemma_text']
sum(df.isna())

4